name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #download repo
      - uses: actions/checkout@v4
      #install java
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
      #selenoid
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      #run tests
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub
